[env:esp32dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
upload_protocol = esp-builtin
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_type = debug
lib_deps =
    links2004/WebSockets@^2.4.0
    h2zero/NimBLE-Arduino@^1.4.0
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
